# Generated by Django 3.1.5 on 2021-01-29 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicblog', '0003_auto_20210129_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='music_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
