# Generated by Django 3.1.5 on 2021-01-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0005_auto_20210130_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
