# Generated by Django 3.1.5 on 2021-02-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0012_post_snippet1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet1',
        ),
    ]
